FROM node:18-alpine

# Create app directory
WORKDIR /frontend

# Install app dependencies
COPY package.json /frontend/package.json
COPY package-lock.json /frontend/package-lock.json

# Run npm install
RUN npm install && npm ls

# Move node_modules wher it should be
RUN mv /frontend/node_modules /node_modules

# Bundle app source
COPY . /frontend

EXPOSE 3000

CMD [ "npm", "start" ]