name: me-hungry
services:
  orders_backend:
    container_name: orders_backend
    image: orders_backend
    build:
      context: ./backend
      dockerfile: ./dockerfile
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: me_hungry
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DEBUG: True
    ports:
      - 8080:8080
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend
          target: /usr/src/app
          action: sync
    volumes:
      - ./backend:/backend
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 1G
        reservations:
          cpus: '0.001'
          memory: 500M

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
      DEBUG: True
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/src
          target: /frontend/src
          action: sync
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.7'
          memory: 700M
          
  postgres:
    image: postgres:13
    container_name: postgres_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: me_hungry
    networks:
      - me_hungry_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    networks:
      - me_hungry_network
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 250M
        reservations:
          cpus: '0.001'
          memory: 150M
 
networks:
  me_hungry_network:
    driver: bridge
 
volumes:
  postgres_data:
  pgadmin_data: