# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as two services called "todo-app" and “todo-database”
# The service “todo-app” is built from the Dockerfile in the /app directory,
# and the service “todo-database” uses the official MongoDB image 
# from Docker Hub - https://hub.docker.com/_/mongo. 
# You can add other services your application may depend on here.
name: me-hungry
services:
  orders_backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: me_hungry
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DEBUG: True
    ports:
      - 8080:8080
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend
          target: /usr/src/app
          action: sync

  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
      DEBUG: True
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: .frontend/
          target: /usr/src/app
          action: sync


  postgres:
    image: postgres:13
    container_name: postgres_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: me_hungry
    networks:
      - me_hungry_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    networks:
      - me_hungry_network
 
networks:
  me_hungry_network:
    driver: bridge
 
volumes:
  postgres_data:
  pgadmin_data: