name: eu_comida
services:
  orders:
    container_name: orders
    image: orders
    build:
      context: ./Orders
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
      DEBUG: True
    ports:
      - 8000:8000
    develop:
      watch:
        - path: ./Orders/requirements.txt
          action: rebuild
        - path: ./Orders
          target: /app
          action: sync
    volumes:
      - ./Orders:/app
      - orders_data:/app/data/
      - /app/App/__pycache__/
    networks:
      - eu_comida_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
        reservations:
          cpus: '0.1'
          memory: 50M
  users:
    container_name: users
    image: users
    build:
      context: ./Users
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
      DEBUG: True
    ports:
      - 8002:8002
    develop:
      watch:
        - path: ./Users/requirements.txt
          action: rebuild
        - path: ./Users
          target: /app
          action: sync
    volumes:
      - ./Users:/app
      - users_data:/app/data/
      - /app/App/__pycache__/
    networks:
      - eu_comida_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
        reservations:
          cpus: '0.1'
          memory: 50M
  restaurant_items:
    container_name: restaurant_items
    image: restaurant_items
    build:
      context: ./Restaurant_items
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
      DEBUG: True
    ports:
      - 8001:8001
    develop:
      watch:
        - path: ./Restaurant_items/requirements.txt
          action: rebuild
        - path: ./Restaurant_items
          target: /app
          action: sync
    volumes:
      - ./Restaurant_items:/app
      - restaurant_items_data:/app/data/
      - /app/App/__pycache__/
    networks:
      - eu_comida_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
        reservations:
          cpus: '0.1'
          memory: 50M

networks:
  eu_comida_network:
    driver: bridge
 
volumes:
  orders_data:
  users_data:
  restaurant_items_data:
