name: eu_comida
services:
  orders:
    container_name: orders
    image: orders
    build:
      context: ./Orders
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
      DEBUG: True
    ports:
      - 8000:8000
    develop:
      watch:
        - path: ./Orders/requirements.txt
          action: rebuild
        - path: ./Orders
          target: /app
          action: sync
    volumes:
      - ./Orders:/app
      - orders_data:/app/data/
      - /app/App/__pycache__/
    networks:
      - euComida_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
        reservations:
          cpus: '0.1'
          memory: 50M
  consumers:
    container_name: consumers
    image: consumers
    build:
      context: ./Consumers
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
      DEBUG: True
    ports:
      - 8002:8002
    develop:
      watch:
        - path: ./Consumers/requirements.txt
          action: rebuild
        - path: ./Consumers
          target: /app
          action: sync
    volumes:
      - ./Consumers:/app
      - consumers_data:/app/data/
      - /app/App/__pycache__/
    networks:
      - euComida_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
        reservations:
          cpus: '0.1'
          memory: 50M
  restaurants:
    container_name: restaurants
    image: restaurants
    build:
      context: ./Restaurants
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
      DEBUG: True
    ports:
      - 8001:8001
    develop:
      watch:
        - path: ./Restaurants/requirements.txt
          action: rebuild
        - path: ./Restaurants
          target: /app
          action: sync
    volumes:
      - ./Restaurants:/app
      - restaurants_data:/app/data/
      - /app/App/__pycache__/
    networks:
      - euComida_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
        reservations:
          cpus: '0.1'
          memory: 50M

networks:
  euComida_network:
    driver: bridge
 
volumes:
  orders_data:
  consumers_data:
  restaurants_data:
