FROM node:18-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

# Run npm install
RUN npm install

# Bundel app source
COPY . .

EXPOSE 8080

CMD [ "npm", "start" ]